### ISSUE TITLE
What is the difference between this repo and orbit-db-access-controller-store?

### ISSUE THREAD

**Issue by RichardLitt** [orbitdb/orbit-db-access-controller-store#1]
I am unsure. 

Let's add this answer to the README.

**Comment by shamb0t** [comment]
This repo is orbit-db-access-controller-store, doesn't look like it is used anywhere and I suspect it is super-ceded by [orbit-db-access-controller](https://github.com/orbitdb/orbit-db-access-controllers/blob/master/src/orbitdb-access-controller.js) in the access-controllers repo. @haadcode can you confirm?

**Comment by haadcode** [comment]
`orbit-db-access-controller-store` was/is an experiment. @shamb0t correct, `orbit-db-access-controller`, super-cedes  `orbit-db-access-controller-store`.

Worth keeping around though, but not sure what would be the best way to do that...

**Comment by RichardLitt** [comment]
If it's not going to be used anymore, we could use the archive feature. It'll stay around, but we won't have to maintain it, no one can open issues, and all current issues will be locked. Want me to do that?

**Comment by haadcode** [comment]
Sure, thanks 👍
